# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/traveldb
spring.datasource.username=travel
spring.datasource.password=travel
spring.datasource.driver-class-name=org.postgresql.Driver
spring.h2.console.enabled=false

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
