spring.application.name=travel

# H2 Console
# http://localhost:8080/h2-console
# jdbc:h2:mem:traveldb
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=false

# Datasource — banco em memória, sem autenticação
spring.datasource.url=jdbc:h2:mem:traveldb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
